### ISSUE TITLE
Windows User

### ISSUE THREAD

**Issue by kuldeepdhyani** [SwordOfAces/aisfor#1]
Hi 
I am a novice in coding & a window user I am seeking exactly this solution can you define some steps on how I can customise it & what all input I should do to make this bot work.
thank you!

**Comment by SwordOfAces** [comment]
Im not in front of the code atm, but the only things that need changing is
that linux and windows handle directory paths differently,  and that i use
chron to fire if off, so you'll need to figure a windows method. I used to
run the script with a "while true, tweet then wait an hour" structure, and
while it's a small script,  it's not ideal.

you'll also need keys from twitter. i may still have a link to Twitter's
info on that but you can google it easily

**Comment by kuldeepdhyani** [comment]
Highly appreciate your time.

I was able to define the path in windows.
Also was able to connect with the twitter.

But it still gives me this error as I am novice trying to figure this out :)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "aisfor_linux.py", line 22, in main
    make_tweet(words, api)
  File "aisfor_linux.py", line 48, in make_tweet
    a_word = _get_word(words)
  File "aisfor_linux.py", line 68, in _get_word
    return words[choice]
IndexError: list index out of range

**Comment by kuldeepdhyani** [comment]
I was able to tweet now but now I want it to be more controlled.
It was a great help though.

**Comment by kuldeepdhyani** [comment]
Thank you a lot.
